steps:
# 1. Instala las dependencias del proyecto
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# 2. Despliega la aplicación a App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

# Esta sección debe estar al mismo nivel que "steps"
options:
  logging: CLOUD_LOGGING_ONLY
